name: Infra Cost Action
on:
  pull_request:
  
jobs:
  infracost:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Infracost
        uses: infracost/actions/setup@v3
        with:
          path: terraform
